### ISSUE TITLE
After dropping IE11: A tracking issue 

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#2457]
This issue is for keeping track of enhancements/changes that should be made immediately after we drop IE11.

This issue is __not__ for discussing whether, when, or how we should/will drop IE11 (see #1578 for that).

### Core

- [x] Use `Element#closest` to implement `Prism.util.isActive`. (see [comment](https://github.com/PrismJS/prism/pull/2434#issuecomment-650354655))
- [x] Remove `Prism.util.currentscript` and use `document.currentScript` instead. (see #2104)

### Plugins

- [x] Promise-based implementation for Autoloader (#1978)
