### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by Golmote** [PrismJS/prism#680]
I just pushed tests for the CSS (3fb26cc72e17632767ff7385dd70022edc06117c) and the JS (26ad4f31076a88762c1b974b9c14098e31b43f15) components.

I'll make PRs for the next ones and will leave them pending for a few days so that anyone can review them. It will also help to keep a better track of what have been done.

I invite any component owner to submit PRs for the language they maintain, this would be of great help! :smiley:

- [x] **Markup** (PR #660 and commit c28d45475d7af63156f7b71b60caff33ddfb769b)
- [x] **CSS** (Commit 3fb26cc72e17632767ff7385dd70022edc06117c)
- [x] **C-like** (PR #689)
- [x] **JavaScript** (Commit 26ad4f31076a88762c1b974b9c14098e31b43f15)
- [x] **ActionScript** (PR #681)
- [x] **Apache Configuration** (PR #682)
- [x] **AppleScript** (PR #683)
- [x] **ASP.NET** (C#) (PR #684)
- [x] **AutoHotkey** (PR #685)
- [x] **Bash** (PR #686)
- [x] **Brainfuck** (PR #687)
- [x] **C** (PR #688)
- [x] **C#** (PR #692)
- [x] **C++** (PR #691)
- [x] **CoffeeScript** (PR #690)
- [x] **CSS Extras** (PR #694)
- [x] **Dart** (PR #693)
- [x] **Eiffel** (PR #695)
- [x] **Erlang** (PR #696)
- [x] **F#** (PR #698)
- [x] **Fortran** (PR #697)
- [x] **Gherkin** (PR #699)
- [x] **Git** (PR #700)
- [x] **Go** (PR #701)
- [x] **Groovy** (PR #704)
- [x] **Haml** (PR #707)
- [x] **Handlebars** (PR #708)
- [x] **Haskell** (PR #709)
- [x] **HTTP** (PR #710)
- [x] **Ini** (PR #711)
- [x] **Jade** (PR #713)
- [x] **Java** (PR #714)
- [x] **Julia** (PR #716)
- [x] **Keyman** (PR #718)
- [x] **LaTeX** (PR #719)
- [x] **Less** (PR #720)
- [x] **LOLCODE** (PR #722)
- [x] **Makefile** (PR #723)
- [x] **Markdown** (PR #724)
- [x] **MATLAB** (PR #726)
- [x] **NASM** (PR #727)
- [x] **NSIS** (PR #728)
- [x] **Objective-C** (PR #729)
- [x] **Pascal** (PR #730)
- [x] **Perl** (PR #733)
- [x] **PHP** (PR #735)
- [x] **PHP Extras** (PR #736)
- [x] **PowerShell** (PR #731)
- [x] **Python** (PR #737)
- [x] **R** (PR #738)
- [x] **React JSX** (PR #715)
- [x] **reST (reStructuredText)** (PR #739)
- [x] **Rip** (PR #740)
- [x] **Ruby** (PR #706)
- [x] **Rust** (PR #741)
- [x] **SAS** (PR #742)
- [x] **Sass (Sass)** (PR #743)
- [x] **Sass (Scss)** (PR #744)
- [x] **Scala** (PR #746)
- [x] **Scheme** (PR #747)
- [x] **Smalltalk** (PR #748)
- [x] **Smarty** (PR #749)
- [x] **SQL** (PR #745)
- [x] **Stylus** (PR #751)
- [x] **Swift** (PR #752)
- [x] **Twig** (PR #753)
- [x] **TypeScript** (PR #755)
- [x] **VHDL** (PR #756)
- [x] **Wiki markup** (PR #757)
- [x] **YAML** (PR #758)

**Comment by nauzilus** [comment]
I am starting to work on [PowerShell tests](https://github.com/nauzilus/prism/tree/tests-powershell), so if you haven't touched that one yet, happily skip over it :+1:

**Comment by Golmote** [comment]
I'll leave it to you, then. Thanks!

**Comment by Golmote** [comment]
All merged! \o/
